name: Deploy production
on:
  push:
    branches:
      - Production
env:
  CI: false

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Get environment'
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          audience: 'sts.amazonaws.com'
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Build TRS App
        run: |
          npm install && npm run build:production
          python process.py --domain https://${{secrets.AWS_PROD_DOMAIN_NAME}} --path Standard-UI/${{secrets.AWS_PROD_PATH}}

      - name: Deploy production app build to S3 bucket
        if: ${{ steps.extract_branch.outputs.branch == 'Production' }}
        run: |
          aws s3 sync build-copy/ s3://${{secrets.AWS_PROD_DOMAIN_NAME}}/Standard-UI/${{secrets.AWS_PROD_PATH}} --delete

      - name: invalidate Cloudfront configuration
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_PROD }}
          PATHS: '/Standard-UI/${{secrets.AWS_PROD_PATH}}/*'